system("wget -O nfl.json 'http://api.fantasy.nfl.com/v1/players/stats?statType=seasonStats&season=2010&week=1&format=json'")
system("cat nfl.json")
library(jsonlite)
df <- fromJSON('nfl.json')
class(df)
class(df$players)
head(df$players,10)
